### ISSUE TITLE
Error: String could not be parsed as XML

### ISSUE THREAD

**Issue by Knallcharge** [Dukecity/CommandSchedulerBundle#17]
The same deprecation error as in j-guyon's bundle happens here. See:
https://github.com/j-guyon/CommandSchedulerBundle/issues/199

This has happened before (see https://github.com/j-guyon/CommandSchedulerBundle/issues/179) which could be fixed with an entry in services.yml.

I wonder why it makes a difference to execute "command list --format=xml" through the CommandParser or via the shell (where the error doesn't show).

Using your version 3 with PHP 7.4.20 and symfony 5.3.3

**Comment by Chris53897** [comment]
Hi. Thank you for reporting this issue. I do not know a solution yet. The problem is that a) the last minute changes of 5.3 produce a lot of deprecation warnings and b) that the deprecation messages and warning are displayed in the stream in the way it is actual used.

The ConsoleOutput differs between StandardOutput and ErrorOutput. But i got an BufferOverflow Error while i try to change the code from StreamOutput.

One solution could be to rewrite the code and use the same code symfony uses while running the command "list ....".
At the moment i am searching for an solution to disable/seperate the ErrotOutput.

**Comment by Knallcharge** [comment]
I played around with the code a bit and found a workaround. Adding
`Debug::enable(E_RECOVERABLE_ERROR & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED, false);`
before the list-command ist run, will suppress the deprecation-warnings in the XML-output and get things working again.
I have created a pull request.
