### ISSUE TITLE
Not yet ready to Symfony 7 ?

### ISSUE THREAD

**Issue by kl3sk** [Dukecity/CommandSchedulerBundle#92]
Hello,

I try to update my project to Sf7 and this bundle seem not ready to.

```bash
    - nesbot/carbon[2.71.0, ..., 2.72.1] require symfony/translation ^3.4 || ^4.0 || ^5.0 || ^6.0 -> found symfony/translation[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.47, v5.0.0, ..., v5.4.31, v6.0.0, ..., v6.4.2] but it conflicts with your root composer.json require (7.0.*).
    - dukecity/command-scheduler-bundle dev-main requires nesbot/carbon ^2.71 || ^3.0 -> satisfiable by nesbot/carbon[2.71.0, 2.72.0, 2.72.1].
    - Root composer.json requires dukecity/command-scheduler-bundle dev-main -> satisfiable by dukecity/command-scheduler-bundle[dev-main].
```

**Comment by kl3sk** [comment]
With an other bundle (pending PR), yours is my last one not compatible with Sf7.

If you need help maybe I can try to.

Thanks in advance

**Comment by knallcharge** [comment]
Some thoughts on this:
Right now updating to Symfony 7 is not possible because nesbot/carbon v3 hat not yet been released. As far as I can see, everything else works with Symfony 7 as well.

Now: Is nesbot/carbon really needed? All it is used for is to display "human diff" of dates in the ListCommand as well as the MonitorCommand (not even in the GUI), that's all. Of course this is highly opinionated, but I don't even use those two commands (or look at their output for that matter), but still, Carbon can be replaced with a simpler class that will just perform the human-readable-conversion.

Removing nesbot/carbon will also get rid of carbonphp/carbon-doctrine-types which is not used at all.

I took a shot at it and replaced Carbon with a simple class (quite old, but still working), you may want to have a look at this: https://github.com/Dukecity/CommandSchedulerBundle/commit/3abe7663cc5449689628bc026bc95b5acebd33fe
I admit, the output of this class sometimes is not really helpful (e.g. just "Tomorrow"), but it removes a lot of overhead and will allow us to use Symfony 7 with this bundle.

Taking one step further back, one could just use `$date->format('translatedDateFormat')` to display the last and next execution date without the human readable-bit altogether. This is done in the GUI already, just a plain date here, so why make the console output fancy? 😄


And one other thing I noticed: Is SchedulerCommand::getNextRunDateForHumans() really necessary? It seems it's just used in the ListCommand while `$lastRunDateText` is already holding the string that it produces, resulting in a duplicate column in the output (last two columns):
![grafik](https://github.com/Dukecity/CommandSchedulerBundle/assets/1715912/7cc7b775-4479-40e5-bfa5-29fc9d9b9df6)
So the method as well as the call in SchedulerCommand could be removed? (already done in my commit mentioned above)

Just my two cents, what do you think?

**Comment by kl3sk** [comment]
Wow, I didn't dive this deep !

Following your comment, if this is confirmed, it look like a good solution.

To replace Carbon (for the purpose used here) it may be replace in an other way with this [dependency](https://github.com/KnpLabs/KnpTimeBundle)

Wait for @Chris53897 for his thoughts.

**Comment by Chris53897** [comment]
Thanks @knallcharge @kl3sk for bringing this up.

I already did work for symfony 7.
My hope was that `nesbot/carbon` v3 did get released sooner.


I used this in my projects to get it work with symfony 7. (not in production)

```
"minimum-stability": "dev",
"prefer-stable": true,

"dukecity/command-scheduler-bundle": "dev-main",
"nesbot/carbon": "^2.72 || ^3.0",
```

I am in favour for https://github.com/KnpLabs/KnpTimeBundle
But this is just a personal choice, because i already use it in my existing projects.

@kl3sk Do you have time to create a PR for this? The changes are already clear with the changes from the commit-link from @knallcharge 

I will try to work this weekend on the open PR's

**Comment by kl3sk** [comment]
Yes I can unless @knallcharge wants to update its ?

**Comment by knallcharge** [comment]
I'll only have time for it next week, so if you like you can go ahead. I'd also vote for the KnpTimeBundle as it also has a twig-filter, so the human readable date could be implemented in the list-view as well. Maybe even with a config-switch so users can choose the way their dates are displayed, but let's first get this working with Symfony 7 before doing the nice-to-have-stuff ;)

**Comment by Chris53897** [comment]
Ready for testing
https://github.com/Dukecity/CommandSchedulerBundle/releases/tag/v6.0.0-beta

**Comment by knallcharge** [comment]
Looks good to me.

**Comment by kl3sk** [comment]
Test on real project looks good to me too.


_Notes:_
For user informations: I need to switch from `symfony/sendinblue-mailer` in favour of `symfony/brevo-mailer`.

Because of company re-brand and package compatibility.
